@baseURL = http://localhost:8080/

# @name getData
GET {{baseURL}}board/posts

###

POST {{baseURL}}board/posts
Content-Type: application/json; charset=UTF-8

{
    "title": "test2",
    "content": "test content2"
}

###

PATCH {{baseURL}}board/posts/{{getData.response.body.posts[0]._id}}
Content-Type: application/json; charset=UTF-8

{
    "title": "test",
    "content": "patch test"
}

###

GET {{baseURL}}board/posts/{{getData.response.body.posts[0]._id}}

###

DELETE  {{baseURL}}board/posts/{{getData.response.body.posts[0]._id}}